cvm-version: 0.0.33
ovmf-version: 0.0.2
cpus: 8
memory: 40960

shim:
  domains:
    - dia.model.tinfoil.sh
  listen-port: 443
  upstream-port: 8003
  origins:
    - https://tinfoil.sh
    - http://localhost:3000

containers:
  - name: "dia"
    image: "ghcr.io/devnen/dia-tts-server"
    args:
      - "-v /mnt/ramdisk/model_cache:/app/model_cache"
      - "-v /mnt/ramdisk/reference_audio:/app/reference_audio"
      - "-v /mnt/ramdisk/outputs:/app/outputs"
      - "-v /mnt/ramdisk/voices:/app/voices"
      - "--env HF_HUB_ENABLE_HF_TRANSFER=1"
      - "--gpus all"