cvm-version: 0.0.32
ovmf-version: 0.0.2
cpus: 8
memory: 40960

shim:
  domains:
    - dia.model.tinfoil.sh
  listen-port: 443
  upstream-port: 8003
  origins:
    - https://tinfoil.sh

containers:
  - name: "dia"
    image: "ghcr.io/devnen/dia-tts-server"